export const HOME = "/home"
export const ADMIN_USERS_PAGE = "/admin/user"
export const PERMISSION_DENIED = "/permission-denied"
export const PAGE_NOT_FOUND = "/404"
export const LOGIN = "/"

export const INVOICE = "/invoice"
export const INVOICE_INPUT = "/invoice/input"
export const INVOICE_OUTPUT_IN_PROJECT = "/invoice/output-in-project"
export const INVOICE_OUTPUT_OUT_OF_PROJECT = "/invoice/output-out-of-project"
export const INVOICE_RETURN_TEAM = "/invoice/return-team"
export const INVOICE_RETURN_OBJECT = "/invoice/return-object"
export const INVOICE_WRITEOFF = "/invoice/writeoff"
export const INVOICE_OBJECT = "/invoice/object"
export const INVOICE_OBJECT_MUTATION_ADD = "/invoice/object/add"
export const INVOICE_OBJECT_DETIALS = "/invoice/object/:id"
export const INVOICE_CORRECTION = "/invoice/correction"

export const REFERENCE_BOOK = "/reference-book"
export const REFERENCE_BOOK_WORKER = "/reference-book/worker"
export const REFERENCE_BOOK_TEAM = "/reference-book/team"
export const REFERENCE_BOOK_MATERIAL = "/reference-book/material"
export const REFERENCE_BOOK_OBJECTS = "/reference-book/object"
export const REFERENCE_BOOK_KL04KV_OBJECT = "/reference-book/object/kl04kv"
export const REFERENCE_BOOK_MJD_OBJECT = "/reference-book/object/mjd"
export const REFERENCE_BOOK_SIP_OBJECT = "/reference-book/object/sip"
export const REFERENCE_BOOK_STVT_OBJECT = "/reference-book/object/stvt"
export const REFERENCE_BOOK_TP_OBJECT = "/reference-book/object/tp"
export const REFERENCE_BOOK_SUBSTATION_OBJECT = "/reference-book/object/substation"
export const REFERENCE_BOOK_OPERATIONS = "/reference-book/operation"
export const REFERENCE_BOOK_MATERIAL_COST = "/reference-book/material-cost"
export const REFERENCE_BOOK_DISTRICT = "/reference-book/district"

export const REPORT = "/report"
export const REPORT_BALANCE_WAREHOUSE = "/report/balance/warehouse"
export const REPORT_BALANCE_TEAM = "/report/balance/team"
export const REPORT_BALANCE_OBJECT = "/report/balance/object"
export const REPORT_BALANCE_OUT_OF_PROJECT = "/report/balance/out-of-project"
export const REPORT_BALANCE_WRITEOFF_WAREHOUSE = "/report/balance/writeoff/warehouse"
export const REPORT_BALANCE_LOSS_WAREHOUSE = "/report/balance/loss/warehouse"
export const REPORT_BALANCE_LOSS_TEAM = "/report/balance/loss/team"
export const REPORT_BALANCE_LOSS_OBJECT = "/report/balance/loss/object"
export const REPORT_BALANCE_WRITEOFF_OBJECT = "/report/balance/writeoff/object"
export const REPORT_INVOICE_INPUT = "/report/invoice/input"
export const REPORT_INVOICE_OUTPUT = "/report/invoice/output"
export const REPORT_INVOICE_OUTPUT_OUT_OF_PROJECT = "/report/invoice/output-of-project"
export const REPORT_INVOICE_RETURN = "/report/invoice/return"
export const REPORT_INVOICE_OBJECT = "/report/invoice/object"
export const REPORT_INVOICE_WRITEOFF_WAREHOUSE = "report/invoice/writeoff/warehouse"
export const REPORT_INVOICE_LOSS_WAREHOUSE = "report/invoice/loss/warehouse"
export const REPORT_INVOICE_LOSS_TEAM = "report/invoice/loss/team"
export const REPORT_INVOICE_LOSS_OBJECT = "report/invoice/loss/object"
export const REPORT_INVOICE_WRITEOFF_OBJECT = "report/invoice/writeoff/object"

export const ADMINISTRATOR_HOME_PAGE = "/admin/home"
export const ADMINISTRATOR_PROJECT = "/admin/project"
export const ADMINISTRATOR_USERS = "/admin/users"

export const IMPORT = "/import"
export const MATERIAL_LOCATION_LIVE = "/material-location-live"

export const WRITEOFF_WAREHOUSE = "/invoice/writeoff/warehouse"
export const LOSS_WAREHOUSE = "/invoice/loss/warehouse"
export const LOSS_TEAM = "/invoice/loss/team"
export const LOSS_OBJECT = "/invoice/loss/object"
export const WRITEOFF_OBJECT = "/invoice/writeoff/object"
